日報、コメント機能を追加
gozasoro/books_app pull request #9
Opened 2020-09-16 19:45 UTC by gozasoro

日報の作成とコメントを付けることができるようになりました。
ナビゲーションメニューに「本一覧」、「ユーザー一覧」、「日報一覧」を追加しました。
一部i18n対応しました。

2020-09-17 13:35 UTC, u1tnk requested changes
ほぼできていると思いますが、何点か指摘がありますのでご確認宜しくお願いします。

2020-09-17 13:35 UTC, u1tnk commented on db/migrate/20200915180143_create_reports.rb
> +      t.date :date
[要対応]
dateというカラム名は何の日付か分からなくなるので良くないです。
created_at等に合わせて xxx_atが一般的です。

2020-09-17 14:36 UTC, gozasoro commented on app/controllers/comments_controller.rb
> +      resource, id = request.path.split("/")[1, 2]
コードを読む方もわかりやすいですし、セキュリティリスク（！）の件でもRailsの機能を使った方がよさそうですね......。
セキュリティリスクの件まで考えていませんでした💦
`book_id`と`report_id`の有無でメソッド内の処理を分けるように修正しました

2020-09-17 14:36 UTC, gozasoro commented on app/controllers/comments_controller.rb
> +      @comment = @commentable.comments.find(params[:id])
`current_user`を使えばコメントが自分のものかどうか確認するメソッドも分けて作る必要がなくなりますね！
修正しました

2020-09-17 14:36 UTC, gozasoro commented on app/controllers/reports_controller.rb
> +  # GET /reports
Booksコントローラーの`show`のコメントも一緒に消しておきました！

2020-09-17 14:36 UTC, gozasoro commented on db/migrate/20200915180143_create_reports.rb
> +      t.date :date
written_atにカラム名を変更しました

2020-09-18 01:18 UTC, u1tnk requested changes
writter_atとか controllerのところとか修正しましたというコメントがあるのに見えないです。push忘れとかですか？
あと、ミスったときに修正ブランチにforce-pushするのは個人的にはやりますが、レビュー指摘された後は修正内容が分からなくなるので、やめた方が良いです。

2020-09-18 01:18 UTC, u1tnk commented on app/controllers/reports_controller.rb
> +  # GET /reports
あ、 showだけじゃなくて 全部という意図でした。まあ課題としては問題無いです。

2020-09-18 11:56 UTC, gozasoro commented
> writter_atとか controllerのところとか修正しましたというコメントがあるのに見えないです。push忘れとかですか？

追加でカラム名変更のマイグレーションファイルを新しく作成して対応したので、`schema.rb`で確認していただけばと思います！
コメントでの説明が足りなかったです、すみません。

レビューではshowではなくindexの`# GET /reports`が表示されてるので、一応showのコメントは消えてます！

> あと、ミスったときに修正ブランチにforce-pushするのは個人的にはやりますが、レビュー指摘された後は修正内容が分からなくなるので、やめた方が良いです。

たしかにレビュー後にforce-pushすると修正したところが全然わからないですね......今後気をつけます！

2020-09-21 14:34 UTC, u1tnk commented
@gozasoro 
金曜から見てなかったので気づくの遅れました 🙏

> 追加でカラム名変更のマイグレーションファイルを新しく作成して対応したので、schema.rbで確認していただけばと思います！
コメントでの説明が足りなかったです、すみません。

あー、diffが多くて気づきませんでした。失礼しました。でしたら大丈夫です！

> レビューではshowではなくindexの# GET /reportsが表示されてるので、一応showのコメントは消えてます！

誤解があるのかなと思いますが、 基本的な `show/create/update/...`等のコメントは基本的に無くて良いですよという意図でした。有っても無くても良いかなってコメントは消した方がすっきりして読みやすくなるというのが目的です。
細かいところなので、今後の参考にして頂ければ特に修正不要です 🙆‍♀️

2020-09-21 14:34 UTC, u1tnk approved these changes

2020-10-02 14:08 UTC, merged